language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
services:
  - docker

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VZAD1Z4vBX0woYGIwAwXa7GHf/PqeV80hzBVJO8Oa5hiSTgSwmvupBMaLpdLobwy9iMjFMBETeiJVG3beW7JExHVBjzyDmGFHYymIQTIgwHpZgL1TyO5b4m69TCPqs21NRGIJhi8FqGp5Jb24gE5JWAxu5xUzhrWzOKsTt326eD4Qvf6vDY260HeX0n7fhuEJCOWcQ7SyA+U9fCb5ROVGBCFxWMYDtafaOo+orDYZnu42TXGB3NJbWX/jtwdKyHECv9XQtQYnG2ev6Y4S7rEbzX9PkBqVRxjH3WUMd0U0VYobU+JLx/bIi1U9iYG3E2ugRWEWnqgIRP9N0wXkIzoVz28Rkwmm8UHdJGI4wvtFsWH9sXN1d6v/YtfoCtLh/MYK9aI/jjk1wwYyjAaVvdEALrgeLiOK3Okd8w1jZEwItfx54Dw8HIBa3fmKyzs7izNUEXbo5jae6QX6jCItW6XqJyjaL4h5xSd15sp/f7pKYRsrKNtBMKTwRgU1ofs6RXq3HJWYMdYYzidGRHTk9cRys/eKELidU5Q+8dq+wnj3tyBbke2LJse+ThLqcX+dFSU86cLykyyVIRNH5jutQXYuRi2W2/kjRRt0FVIOoR1+mzVyd5tW3x37I5LJkCcr3CXNvD/kAUsO0o4Z1bizjHOe2W1yayxZ0j5+5r+fXMnZvo="

before_install:
  - docker pull ubuntu:xenial
  - docker run --name xenial -dti ubuntu:xenial bash
  - docker cp . xenial:/root/source
  - docker exec xenial apt-get -qq update
  - docker exec xenial apt-get -qq install software-properties-common
  - docker exec xenial apt-add-repository ppa:nimoov/llvm-cmake
  - docker exec xenial apt-get -qq update
  - docker exec xenial apt-get -qq install llvm-3.8 llvm-3.8-dev llvm llvm-dev clang-3.8 clang-3.8-dev clang cmake bison flex zlib1g-dev libcppunit-1.13-0v5 libcppunit-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
    # Debug Data:
  - docker exec xenial make --version
  - docker exec xenial clang --version
  - docker exec xenial gcc-5 --version
  - docker exec xenial cmake --version

install:
  - docker exec xenial /bin/sh -c "mkdir /root/source/build && cd /root/source/build"
  - docker exec xenial /bin/sh -c "cd /root/source/build && cmake .. -DDEBUG=1 -DCCPP=1 -DCLLVM=1 -DCHASKELL=1 -DCGNUASM=1 -DJIT=1"
  - #Test C
  - docker exec xenial /bin/sh -c "mkdir /root/source/test-c && cd /root/source/test-c"
  - docker exec xenial /bin/sh -c "cd /root/source/test-c && cmake .. -DDEBUG=1 -DCCPP=1 -DCLLVM=0 -DCHASKELL=0 -DCGNUASM=0 -DJIT=0 -DTESTS=1"
script:
  - docker exec xenial /bin/sh -c "cd /root/source/build && make -j 8"
  - docker exec xenial /bin/sh -c "cd /root/source/build && make install"
  - #Test C
  - docker exec xenial /bin/sh -c "cd /root/source/test-c && make tests -j 8"
  - docker exec xenial /bin/sh -c "cd /root/source/test-c && make install"

after_script:
  - pwd
  - cat /home/travis/build/prozum/sppl/build/cov-int/build-log.txt
  - cat /home/travis/build/prozum/sppl/build/cov-int/scm_log.txt 

addons:
  coverity_scan:
    project:
      name: "prozum/sppl"
      description: "Build submitted via Travis CI"
    notification_email: nimoov@prozum.dk
    build_command_prepend: "cov-configure --gcc --compiler /usr/bin/g++ --comptype gcc"
    build_command:   "make -j 8"
    branch_pattern: coverity

notifications:
  email: false
