language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "meodC/ecpzTzHH0PWOt1Oq0FEsZT3D+zLejtLhbBY9WemnArsF8DbQdXuYgxKx9OMfK6OF40y/2tH4Jsxm+zGjbhV2VDndbxT6MfYjUdfXBpudTzVFF+QUhZoLbK4alqwXdC3QyMEjIj3+ZDxw/Zh1lpVmzY/akDtOo16xPEAG/Ev3c6DZ6YDnapCUxwgSkujiMn7gB8pxUJgHEniGqh9FXXsbPdyBedkbZu6b9uyQGWSoFtCn7Be3vzgC1+3DlERWoe7yWD0lHLUOopG+t1dZv8UCcteGZg3aKVScPHcR5t3HrRRAI5m/hBIV1H6zWOInjYvqH9W5PPo8x4cup+Hme1F0dclPlSHFn/1Yn3fMSff6ep+llXBjdWot94B29TpPZCfhyihyFb+3K3o37NW3HF/KMWyNmSYntfxS6VmzZgO01RLuvvBi0xnUEsmKRO5vIg0QjcQAzCl6fRd7TkiFYkf5zNcMwYr17czWG7DXPRR9+Yp3MODR7w3I34PXHBKxNPgcKQJlLyCLPUsjMl2S4oJ2OL3vGV/z2gAHNJ3+7EzJEgkugWK1kvtjwCxvvwEMfy2+y/avaGHrD/DkHJkK14K2rUuZIwm385EdvdMqus+zC62PCjgfJzmUoE53WnggM73RfEMax9nzHLmEMFzN9AA6ZMXJrA9QtHu08XFAM="


before_install:
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee --append /etc/apt/sources.list
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install clang-3.7 gcc-5 g++-5 libstdc++-5-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    # Debug Data:
  - ls
  - make --version
  - clang --version
  - gcc --version
  - cmake --version

install:
  - mkdir build && cd build
  - cmake ..

script:
  - make -j 8
  - sudo make install

addons:
  coverity_scan:
    project:
      name: "prozum/sppl"
      description: "Build submitted via Travis CI"
    notification_email: nimoov@prozum.dk
    build_command_prepend: "make clean"
    build_command:   "make -j 8"
    branch_pattern: coverity

notifications:
  email: false
