language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VZAD1Z4vBX0woYGIwAwXa7GHf/PqeV80hzBVJO8Oa5hiSTgSwmvupBMaLpdLobwy9iMjFMBETeiJVG3beW7JExHVBjzyDmGFHYymIQTIgwHpZgL1TyO5b4m69TCPqs21NRGIJhi8FqGp5Jb24gE5JWAxu5xUzhrWzOKsTt326eD4Qvf6vDY260HeX0n7fhuEJCOWcQ7SyA+U9fCb5ROVGBCFxWMYDtafaOo+orDYZnu42TXGB3NJbWX/jtwdKyHECv9XQtQYnG2ev6Y4S7rEbzX9PkBqVRxjH3WUMd0U0VYobU+JLx/bIi1U9iYG3E2ugRWEWnqgIRP9N0wXkIzoVz28Rkwmm8UHdJGI4wvtFsWH9sXN1d6v/YtfoCtLh/MYK9aI/jjk1wwYyjAaVvdEALrgeLiOK3Okd8w1jZEwItfx54Dw8HIBa3fmKyzs7izNUEXbo5jae6QX6jCItW6XqJyjaL4h5xSd15sp/f7pKYRsrKNtBMKTwRgU1ofs6RXq3HJWYMdYYzidGRHTk9cRys/eKELidU5Q+8dq+wnj3tyBbke2LJse+ThLqcX+dFSU86cLykyyVIRNH5jutQXYuRi2W2/kjRRt0FVIOoR1+mzVyd5tW3x37I5LJkCcr3CXNvD/kAUsO0o4Z1bizjHOe2W1yayxZ0j5+5r+fXMnZvo="



before_install:
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty main" | sudo tee --append /etc/apt/sources.list
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install clang-3.8 gcc-5 g++-5 libstdc++-5-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
    # Debug Data:
  - make --version
  - clang-3.8 --version
  - gcc-5 --version
  - cmake --version

install:
  - mkdir build && cd build
  - cmake .. -DDEBUG=1

script:
  - make -j 8
  - sudo make install

after_script:
  - pwd
  - cat /home/travis/build/prozum/sppl/build/cov-int/build-log.txt
  - cat /home/travis/build/prozum/sppl/build/cov-int/scm_log.txt 

addons:
  coverity_scan:
    project:
      name: "prozum/sppl"
      description: "Build submitted via Travis CI"
    notification_email: nimoov@prozum.dk
    build_command_prepend: "cov-configure --gcc --compiler /usr/bin/g++ --comptype gcc"
    build_command:   "make -j 8"
    branch_pattern: coverity

notifications:
  email: false
