language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Pw3YB2IfOpJpjTKsT2SMYhph3yKUxAvd2NwlKm39VCmkc3Jy4fAARuURA+QoZC9JaOIOOEzmD6xCIt49eBPVha5RRX1tawSh7UPVWWKs88dp8IEuGVUEdKOoWwtLTEhpw95BEEQ4EnwQH89lGt0zRi3/KBeSTZM9/062VupzjgA9vLbpJoshpaIZ8/osG23g2aojMtOMMAC7qxioa/iJJRQzURJY/Lmm2lKB00gap4CuYXC5Yc239r8YlRkFw7Ac2M8pI6aUTFCPP5gvVRSGnpV/bDJVMrReaA0RMOPRjg1wEw42xdCbBJEzU/WQO0Z7MwwLbHD/cXmeSTwLwCFhFOOeJPG/o3jc5u2xMz3h0MEf44iWBdvOhLXJbdUX2zLnWjDY7ulYMBWq/ebbhslS/XwS1jadNfwFMj2aChtwCCl92cb01Yag4Vuhksj4J1Mqi11ol1/o9ofl3pmn3g7BE+HK7dJRK1VjFmirTeoK27ZNOPV+h26rbKJfNlsrvlUL9prAGd4zjRr5Wh0Wgt0+QyiheWQjPO9RRQAkkypqo+t8ILvUDb9WvwaOQM0UPEak12rNtgJXvaEeUwWgH/skEU2OO2ato6H/RNbtOqa/FkNl3giKBFDBvi/jir8yZIQNf6omcQbCa2jQDzL6Yukt0RP5zaiRfEMZ8ulenyrUG1E="

before_install:
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee --append /etc/apt/sources.list
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install clang-3.7 gcc-5 g++-5 libstdc++-5-dev
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    # Debug Data:
  - ls
  - make --version
  - clang --version
  - gcc --version
  - cmake --version

install:
  - mkdir build && cd build
  - cmake ..

script:
  - make -j 8
  - sudo make install

addons:
  coverity_scan:
    project:
      name: "nimoov/next-lang"
      description: "Build submitted via Travis CI"
    notification_email: nimoov@prozum.dk
    build_command_prepend: "make clean"
    build_command:   "make -j 8"
    branch_pattern: coverity

notifications:
  email: false
